### ISSUE TITLE
[whales, task 3] Error: no such option: -s 

### ISSUE THREAD

**Issue by pknut** [neptune-ml/minerva-training-materials#77]
In task 3:
> This is an alignment subtask so add -s classification to the execution command

`neptune run -- submit --problem whales --task_nr 3 -s classification`

The above throws an error:

`Error: no such option: -s `

**Comment by kamil-kaczmarek** [comment]
Hi @pknut, this is an artifact from the previous version of the CLI. Changes that removed this were merged in #78
